services:
  backend:
    build: .  # 현재 디렉토리에서 빌드
    image: backend-image
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul  # 타임존 설정
    networks:
      - project-network

networks:
  project-network:
    external: true  # 외부에 이미 정의된 project-network를 사용